fix: generate random chain ids when bor/heimdall chain ids are not provided
maticnetwork/matic-cli pull request #140
Opened 2023-01-17 09:27 UTC by Raneet10

# Description

Earlier when  bor/heimdall chain Ids were not provided in `.env ` , express-cli didn't generate a random one. This PR fixes that.

# Changes

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] New test case for remote devnet

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [x] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing

- [ ] I have tested this code manually on local environment
- [x] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai

2023-01-17 10:47 UTC, marcello33 requested changes
Need to make it work with edge cases too (empty, null, undefined, numbers...)

2023-01-17 12:05 UTC, Raneet10 commented
> Need to make it work with edge cases too (empty, null, undefined, numbers...)

Yes it's more appropriate to do these checks in the env validator

2023-01-30 15:47 UTC, marcello33 approved these changes

2023-01-30 16:32 UTC, 0xsharma approved these changes

2023-01-30 16:33 UTC, merged